# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'ZBDemo' do
pod 'Alamofire'
pod 'Kingfisher'
pod 'Moya/RxSwift', '~> 10.0'
pod 'SwiftyJSON'
end
